//! This file was generated by running generate_params.py
// The number of CEX asset balances for each user account
pub const N_ASSETS: usize = 1;
// A Merkle sum tree helper dimension parameter used to lay out the cells deoending on the number of assets
pub const MST_WIDTH: usize = 3 * (1 + N_ASSETS);
// Poseidon hasher parameter for Rate and Length used in MST nodes (nodes take left hash, left assets, right hash, right assets as inputs)
pub const R_L_NODE: usize = 2 * (1 + N_ASSETS);
// Poseidon hasher parameter for Width used in MST nodes
pub const WIDTH_NODE: usize = R_L_NODE + 1;
// Poseidon hasher parameter for Rate and Length used in MST entries (aka levaes, they only take one hash and one set of assets as input)
pub const R_L_ENTRY: usize = 1 + N_ASSETS;
// Poseidon hasher parameter for Width used in MST entries
pub const WIDTH_ENTRY: usize = R_L_ENTRY + 1;
