//! This file was generated by running generate_params.py
pub const N_ASSETS: usize = 1;
pub const MST_WIDTH: usize = 3 * (1 + N_ASSETS);
pub const R_L_NODE: usize = 2 * (1 + N_ASSETS);
pub const WIDTH_NODE: usize = R_L_NODE + 1;
pub const R_L_ENTRY: usize = 1 + N_ASSETS;
pub const WIDTH_ENTRY: usize = R_L_ENTRY + 1;
