//! This file was generated by running generate_params.py
pub const N_ASSETS: usize = 1;
pub const MST_WIDTH: usize = 3 * (1 + N_ASSETS);
pub const POSEIDON_RATE: usize = 2 * (1 + N_ASSETS);
pub const POSEIDON_WIDTH: usize = POSEIDON_RATE + 1;
pub const POSEIDON_LENGTH: usize = POSEIDON_RATE;
